-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Gazdă: localhost:3306
-- Timp de generare: iul. 06, 2023 la 08:13 PM
-- Versiune server: 10.5.20-MariaDB
-- Versiune PHP: 7.3.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Bază de date: `id20929942_biblioteca`
--
CREATE DATABASE IF NOT EXISTS `id20929942_biblioteca` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE `id20929942_biblioteca`;

-- --------------------------------------------------------

--
-- Structură tabel pentru tabel `carte`
--

CREATE TABLE `carte` (
  `Id` mediumint(9) NOT NULL,
  `Autor` varchar(50) NOT NULL,
  `Titlu` varchar(100) NOT NULL,
  `Editura` varchar(50) NOT NULL,
  `Anul_aparitiei` smallint(6) NOT NULL,
  `Nr` smallint(6) NOT NULL,
  `Descriere` text DEFAULT NULL,
  `Categorie` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Eliminarea datelor din tabel `carte`
--

INSERT INTO `carte` (`Id`, `Autor`, `Titlu`, `Editura`, `Anul_aparitiei`, `Nr`, `Descriere`, `Categorie`) VALUES
(1, 'Costache Negruzzi', 'Alexandru Lăpușneanu', 'Corint', 2007, 3, 'Opera lui Costache Negruzzi evoc&#259; momente din cea de-a doua domnie a lui Alexandru L&#259;puşneanul (1564-1569), complet&#226;nd realitatea, sursa documentar&#259; din cronici, cu ficţiunea. Considerat&#259; prima nuvel&#259; istoric&#259; rom&#226;neasc&#259;, opera Alexandru L&#259;puşneanul apare &#238;n anul 1840 &#238;n revista „Dacia literar&#259;”, &#238;ncadr&#226;ndu-se &#238;n programul romantic al acesteia, prin valorificarea unor fapte istorice şi prin crearea de tipuri vii, puternice, sf&#226;şiate l&#259;untric de manifest&#259;ri adesea contradictorii.', 'Beletristică'),
(2, 'Neagu Djuvara', 'Amintiri si povesti mai deocheate', 'Humanitas', 2009, 1, 'Fiecare carte, asemenea fiecărui om, are o poveste a ei. E-adevărat însă că, în timp ce poveștile oamenilor ies mai ușor la lumină, poveștile cărților sunt doar arareori cunoscute. Și Poveștile mai deocheate ale lui Neagu Djuvara au o... poveste a lor. Într-o bună zi, venit la editură să discute sumarul unei viitoare cărți despre boierimea română, autorul a lăsat și un manuscris pe a cărui primă filă era scris (cu roșu!) ,,pentru după moartea mea\". Imposibil de trecut peste o asemenea hotărâre! Și totuși, cum să le întârzii cititorilor bucuria de a se reîntâlni cu un povestitor atât de plin de har cum e Neagu Djuvara! Așa că, după nu puține și nici ușoare exerciții de persuadare, Neagu Djuvara s-a lăsat înduplecat și ne-a îngăduit să adunăm în volum cele patru povești risipite într-o revistă. Mai mult chiar, acum, dacă tot aveau să devină carte, poveștile s-au îmbogățit cu noi, spumoase și irezistibil istorisite întâmplări. Ca și Amintirile din pribegie, aceste Amintiri și povești mai deocheate sunt un prilej minunat de a călători în timp, căci memoria lui Neagu Djuvara, ajutată de fermecătoarea sa limbă română, e cea mai bună călăuză - și, de astă dată, o călăuză mai pusă pe șotii și dispusă la indiscreții ca oricând.', 'Memorii,biografii,jurnale'),
(3, 'Adrian Costache', 'Atlasul literaturii române', 'Cartographia', 2005, 2, 'Atlasul literaturii rom&#226;ne este singurul material didactic editat &#351;i comercializat &#238;n Rom&#226;nia, care con&#355;ine informa&#355;ii &#351;i elemente cartografice despre originea, via&#355;a &#351;i activitatea literar&#259; a marilor c&#259;rturari rom&#226;ni. Tematica &#351;i informa&#355;iile transmise prin intermediul atlasului sunt realizate &#238;n conformitate cu programa &#351;colar&#259; actual&#259;, beneficiind totodat&#259; de acreditarea emis&#259; de c&#259;tre Ministerul Educa&#355;iei &#351;i Cercet&#259;rii.\r\n\r\nAtlasul este destinat elevilor din &#238;nv&#259;&#355;&#259;m&#226;ntul gimnazial &#351;i liceal &#351;i cuprinde informa&#355;ii referitoare la:\r\n- Etapele literaturii rom&#226;ne, oferind o perspectiv&#259; asupra evolu&#355;iei &#351;i dezvolt&#259;rii literaturii de-a lungul timpului.\r\n- Curentele literare rom&#226;ne&#351;ti, prezentate &#238;n paralel cu cele europene, oferind o viziune comparativ&#259; &#351;i contextualizat&#259; a evolu&#355;iei literaturii rom&#226;ne.\r\n- Revistele literare importante &#351;i itinerarele literare, eviden&#355;iind importan&#355;a publica&#355;iilor periodice &#238;n promovarea &#351;i dezvoltarea culturii &#351;i literaturii rom&#226;ne.\r\n- Via&#355;a &#351;i activitatea literar&#259; a marilor poe&#355;i &#351;i scriitori rom&#226;ni, prezent&#226;nd biografii, opere literare &#351;i contribu&#355;ia acestora la patrimoniul cultural rom&#226;nesc.\r\n\r\nPrin intermediul acestui atlas, elevii au acces la informa&#355;ii relevante &#351;i actualizate despre literatura rom&#226;n&#259;, care &#238;i ajut&#259; s&#259; &#238;n&#355;eleag&#259; mai bine contextul cultural &#351;i literar &#238;n care s-au dezvoltat marii autori rom&#226;ni. Atlasul contribuie la formarea unei viziuni integrate &#351;i la cultivarea dragostei pentru literatur&#259; &#351;i patrimoniul cultural al Rom&#226;niei.\r\n', 'Manuale și auxiliare școlare'),
(4, 'Mark Twain', 'Aventurile lui Tom Sawyer', 'Maxim Bit', 2004, 2, 'Mai toate aventurile descrise &#238;n aceast&#259; carte sunt &#238;nt&#226;mpl&#259;ri adev&#259;rate; una sau dou&#259; dintre ele sunt ale mele proprii, celelalte sunt ale fo&#351;tilor mei colegi de &#351;coal&#259;.\r\nHuck Finn este un personaj real: Tom Sawyer de asemenea, dar nu este un personaj de sine st&#259;t&#259;tor, c&#259;ci figura lui e o &#238;mbinare de caractere.\r\nSupersti&#355;iile ciudate de care amintesc aici erau foarte r&#259;sp&#226;ndite printre copiii &#351;i sclavii din vestul Americii, cu treizeci-patruzeci de ani &#238;nainte de a scrie aceast&#259; carte.\r\nDe&#351;i am scris povestirea de fa&#355;&#259; mai mult pentru a d&#259;rui c&#226;teva clipe de destindere celor tineri, n&#259;d&#259;jduiesc c&#259; ea va fi luat&#259; &#238;n seam&#259; &#351;i de oamenii mari, c&#259;ci inten&#355;ia mea este \r\ns&#259; le reamintesc &#351;i lor &#238;n chip pl&#259;cut cum erau odinioar&#259;, cum sim&#355;eau, cum g&#226;ndeau, ce vorbeau &#351;i ce nazb&#226;tii ciudate puneau uneori la cale. – \r\nMark Twain\r\n', 'Beletristică'),
(5, 'George Topîrceanu', 'Balade vesele și triste', 'Maxim Bit', 2006, 8, 'Cărți clasice, alese cu grijă, la care ne întoarcem adesea, pentru noile generații de elevi, profesori, părinți.\r\n\r\nExpresive, amuzante, tandre, înduioșătoare, colorate în cele mai frumoase nuanțe, poeziile lui G. Topîrceanu ne invită să le descoperim ori să le redescoperim și să le savurăm fără rețineri. Balada unui greier mic, Sfârșit de vară, Rapsodii de toamnă sunt doar câteva dintre instantaneele din albumul de fotografii al naturii pe care poetul le-a surprins cu talent și cu o sclipire poznașă în priviri.\r\n', 'Beletristică'),
(6, 'Mihail Drumes', 'Cazul Magheru', 'Art ', 2006, 4, 'Aproape toți comentatorii au observat că Victor Petrini este un alter-ego al lui Marin Preda. Dacă Marin Preda, imediat după apariția romanului, ar fi declarat Victor \'\'Petrini c\'est moi\'\', nimeni nu ar fi considerat dezvăluirea senzațională (ca în cazul lui Flaubert), întrucât corespondența dintre scriitor și personaj este evidentă. Trebuie făcute însă câteva precizări. Victor Petrini reprezintă ceea ce a rămas neexprimat din personalitatea lui Marin Preda, după ce acesta și-a scris romanele cu Ilie Moromete. Primul Marin Preda era sobru și practica o disciplină artistică de fier. Descria situații și povestea întâmplări, fără să le comenteze. Iar el însuși nu apărea în prim-plan. Cel de-al doilea Marin Preda, reprezentat de Victor Petrini, are comportamentul unui bătrân care iese în lume cu hainele șifonate și cu cravata strâmbă, manifestând în plus tendința de a vorbi prea mult despre sine, fără să observe - sau să-i pese - că-i agasează pe cei din jur. - Alex Ștefănescu.', 'Beletristică'),
(7, 'Marin Preda', 'Cel mai iubit dintre pământeni vol.1', 'Cartex', 2006, 1, 'Personajul central al trilogiei, Victor Petrini, adună date biografice și experiențe-limită ale unor personalități reale cunoscute de Marin Preda (I.D. Sârbu, Ion Caraion, Romulus Dianu), precum și ale autorului însuși, rămânând un personaj sfâșiat, dual, atât ca cel care i-a dat naștere, cât și în sine. \"Era tâlhosilor\" și \"Noua Gnoză\" exprimând un refuz și o speranță, ar fi putut genera, în ultima parte a trilogiei, acea sinteză originală a cărei absență este regretată și de Noica.\r\n\r\nOricum, trebuie să regretăm faptul că eroul principal din \"Cel mai iubit dintre pământeni\" nu este transfigurat într-un sens propriu, adică printr-o nouă față a temei universale a iubirii, care să culmineze romanul. În momentul final, când ni se spune că \"ea\" este totul, nu poate fi vorba de iubirea de totdeauna, nici de cele trei din roman, nici de iubirea lui Tristan, de iubirea creștină către oameni sau iubirea indiană către natură și zei. Dar poate fi vorba de toate acestea la un loc, într-un cuget de pământean ales.\r\n\r\nCezar Ivanescu', 'Beletristică'),
(8, 'Marin Preda', 'Cel mai iubit dintre pământeni vol.2', 'Cartex', 2006, 1, 'Personajul central al trilogiei, Victor Petrini, adună date biografice și experiențe-limită ale unor personalități reale cunoscute de Marin Preda (I.D. Sârbu, Ion Caraion, Romulus Dianu), precum și ale autorului însuși, rămânând un personaj sfâșiat, dual, atât ca cel care i-a dat naștere, cât și în sine. \"Era tâlhosilor\" și \"Noua Gnoză\" exprimând un refuz și o speranță, ar fi putut genera, în ultima parte a trilogiei, acea sinteză originală a cărei absență este regretată și de Noica.\r\n\r\nOricum, trebuie să regretăm faptul că eroul principal din \"Cel mai iubit dintre pământeni\" nu este transfigurat într-un sens propriu, adică printr-o nouă față a temei universale a iubirii, care să culmineze romanul. În momentul final, când ni se spune că \"ea\" este totul, nu poate fi vorba de iubirea de totdeauna, nici de cele trei din roman, nici de iubirea lui Tristan, de iubirea creștină către oameni sau iubirea indiană către natură și zei. Dar poate fi vorba de toate acestea la un loc, într-un cuget de pământean ales.\r\n\r\nCezar Ivanescu', 'Beletristică'),
(9, 'Marin Preda', 'Cel mai iubit dintre pământeni vol.3', 'Cartex', 2006, 1, '\"Cel mai iubit dintre pământeni\" este cel mai mare efort creator pe care l-am depus până în prezent. Pot să spun că, dacă aș fi fost mai tânăr, n-aș fi putut să scriu această carte. Este deci rodul maturității biologice, dar și artistice. Acest efort a scos la iveală multe secrete ale ființei mele și sper ca imaginația mea să nu fi fost secatuită. Din această pricină, adică din această stare de spirit de după scriere - stare de spirit care sper să fie trecătoare - mi-e greu să-mi imaginez că m-aș mai putea angaja la o lucrare de astfel de proporții. [...] Am amânat \"Delirul\", volumul doi, pentru că mi-am dat seama că, dacă nu scriu acum această carte, adică trilogia care a ieșit, s-ar putea să n-o mai scriu niciodată. De ce trebuia neapărat scrisă? Cine o citește nu mai pune această întrebare - nici șieși și nici scriitorului. - Marin Preda', 'Beletristică'),
(10, 'Mircea Cărtărescu', 'De ce iubim femeile', 'Humanitas', 2006, 1, 'E limpede că și adulții au nevoie de povești. Numai că zânele lor și-au scurtat rochiile, și-au tăiat părul care le ajungea cândva la călcâie și au învățat să fie femei, ceea ce este mult mai complicat și mai periculos decât meseria de zână. Un mănunchi de povești cu femei așadar, spuse simplu, captivant, de un povestitor al căruiă viată seamănă ca două picături de rouă cu a lui Mircea Cărtărescu. În fiecare poveste este un sâmbure de neobișnuit care stă ascuns în carnea obișnuitului, în \"ordinar\" o sămânță de extraordinar care dă rod epic. Un omagiu (adesea în sensul cel mai concret, erotic, al cuvântului) adus femeilor \"pentru că sunt femei\". Întrebările criticului: Cine spunea că scriitorul român a uitat să povestească? Cine spunea că este misogin?\r\n\r\n', 'Beletristică'),
(11, 'Marin Buca', 'Dicționar de antonime', 'Vox', 2005, 1, 'Prin acuratețea demersului științific, Dicționarul de antonime este o lucrare de referință în domeniu, care se adresează elevilor, studenților, cadrelor didactice și tuturor persoanelor interesate de cunoașterea resurselor expresive ale limbii române.\r\n\r\nDicționarul cuprinde:\r\n\r\n- Peste 5000 de perechi antonimice.\r\n- Prezentarea unor noi tipuri structurale și semantice de antonime.\r\n- O mai largă reflectare a raporturilor antonimiei cu polisemia, sinonimia și derivarea.\r\n- Pentru exemplificare, citate din opere literare.\r\n', 'Manuale și auxiliare școlare'),
(12, 'Marin Buca', 'Dicționar de expresii românești', 'Vox', 2005, 1, 'Dicționarul de expresii românești se adresează elevilor, studenților, cadrelor didactice, publicului cu preocupări lingvistice mai largi și cititorilor care manifestă interes față de cunoașterea resurselor expresive ale limbii române, constituind un util instrument de lucru și de informare. După aprecierea marelui lingvist român Lazăr Șăineanu, \"Nimic nu poate scoate mai bine în relief fiziognomia specială a unui popor ca un studiu asupra expresiilor sale metaforice. În aceste creațiuni rezidă tot geniul unei limbi și ele dau tiparul propriu fiecărei idiomae.\"\r\n\r\nObiectivul Dicționarului este să pună la dispoziția celor interesați expresiile folosite frecvent în vorbirea curentă, în literatura clasică și contemporană și, mai ales, în literatura populară, ajutându-i să-și însușească corect structura gramaticală și lexicală a acestui tezaur de expresivitate lingvistică. Dicționarul are un caracter selectiv, cuprinzând în primul rând expresii excerptate din Dicționarul explicativ al limbii române, completate cu expresii preluate din alte dicționare și din lucrări de specialitate.\r\n\r\nExpresiile sunt prezentate într-o formă sistematizată și accesibilă atât în structura gramaticală, cât și lexicală, consfințită de uzul vorbitorilor limbii române și înregistrată de dicționare. Explicațiile expresiilor, simple și concise, sunt preluate din dicționare sau sunt formulate pe baza acestora. Nuanțele de sens ale expresiilor au fost separate în cadrul definiției prin punct și virgulă, iar sensurile mai îndepărtate au fost notate prin a; b; c. Adesea, după definiția propriu-zisă, urmează o expresie sinonimă.\r\n', 'Manuale și auxiliare școlare'),
(13, 'Alexandru Mitru', 'Din marile legende ale lumii vol.1', 'Vox', 2012, 1, 'Antologia miturilor fundamentale ale omenirii\r\n\r\nDin marile legende ale lumii adună laolaltă mituri celebre ale omenirii. Alexandru Mitru rescrie povești în care personaje legendare își demonstrează vitejia, lupta pentru dragoste și în care prietenia învinge ura, iar onoarea este mai presus de orice. Textul acestei ediții îi urmărește îndeaproape pe acela al volumului publicat în 1976 de Editura Junimea.\r\n\r\nNoaptea, Ghilgames visa iar. Ploua cu sânge și cu foc. Focul se stinse într-un târziu și rămase numai cenușă.\r\nPrevestirile erau rele. Enkidu se cutremura.\r\n- Dacă te temi, întoarce-te!\r\n- Nu mă întorc, rămân cu tine. Prietenia îmi este mai scumpă decât viața, Ghilgames.\r\n\r\nDin marile legende ale lumii este o carte de neratat. Alexandru Mitru repovestește unele dintre cele mai frumoase poeme epice și legende ale lumii, valorificând, în cazul creațiilor anonime, cele mai îndepărtate izvoare literare, pe care le aduce astfel mai aproape de cititori.\r\n\r\nVolumul I conține legende despre:\r\n• Ghilgames\r\n• Cneazul Igor\r\n• Roland\r\n• Sigfrid și Crimhilda\r\n• Cidul\r\n', 'Beletristică'),
(14, 'Adrian Neculau', 'Educația Adulților', 'Polirom', 2004, 1, 'Educația adulților pornește de la experiența românească interbelică în ceea ce privește pedagogia socială, pentru a oferi un model și a stimula extinderea ofertei pedagogice către categoriile defavorizate, atât prin regândirea instituțiilor de formare, cât și dincolo de sistemul instituțional de educație. Se dezvoltă astfel concepția pedagogiei sociale ca activitate de asistență a grupurilor neglijate sau abandonate, lipsite de consiliere socială și educativă, ca acțiune de sprijinire și îndrumare a tinerilor, adulților, femeilor.\r\n\r\nCuprins:\r\nDe la pedagogia socială la educația adulților\r\n• Eminescu – un sistem de pedagogie socială\r\n• Seminarul Pedagogic al Universității din Iași (1899-1948)\r\n• Serviciul Social – o școală de educație socială\r\n• Mișcarea cooperatistă și efectele sale social-pedagogice\r\n', 'Sociologie'),
(15, 'Alexandru Dumas', 'Invitație la vals', 'Art ', 2006, 1, '\"Invitația la vals\" este unul dintre cele mai apreciate romane ale literaturii interbelice, iar în cei aproape nouăzeci de ani scurși de la prima sa apariție, în 1936, a fost publicat în zeci de ediții. Drumeș spune povestea de dragoste dintre Tudor și Micaela, o experiență măcinată de excese emoționale, gelozie și jocuri ale seducției.\r\n\r\nTudor, pentru care femeile nu mai reprezintă un mister, este intrigat de lipsa de interes a Micaelei și vrea cu orice preț să o seducă. Tânăra studentă, aparent neclintită în fața declarațiilor acestuia, se lasă atrasă într-un joc al voluptății al cărui reguli îi sunt necunoscute. Dragostea celor doi protagoniști, prinși în valtoarea pasiunii, este o continuă luptă de cucerire, devoratoare și autodistructivă.\r\n\r\nTudor și Micaela - personajele centrale ale acestui roman - nu se gândesc că \"an eye for an eye makes the whole world blind\", iar setea lor de răzbunare te face să te întrebi unde se termină dragostea și încep orgoliile. Și, mai ales, până unde poți merge mânat de ambiția diabolică de a-l face să sufere pe omul pe care-l iubești cel mai mult.\r\n', 'Beletristică'),
(16, 'Salvador Dali', 'Jurnalul unui geniu', 'Humanitas', 2012, 1, 'Dali are conștiința propriului geniu. Până la vertij. Pare să fie un sentiment intim foarte reconfortant. Părinții l-au numit Salvador tocmai pentru că era menit să salveze pictura amenințată cu moartea de către arta abstractă, de suprarealismul academic, de dadaism și, în general, de toate \"ismele\" anarhice. Jurnalul este, deci, monumentul pe care Dali îl înalță gloriei personale. Lipsește din paginile lui orice urmă de modestie...\r\n', 'Memorii,biografii,jurnale'),
(17, 'Mircea Eliade', 'La Țigănci', 'Cartex', 2006, 1, 'Încă din adolescență mi-a plăcut să scriu nuvele, povestiri și chiar romane fantastice. De fapt, descopeream subiectul romanului sau al nuvelei pe măsură ce scriam.\r\nUniversurile paralele pe care le dezvăluia povestirea erau rodul imaginației creative, nu al erudiției sau al hermeneuticii pe care o stăpânea istoricul religiilor comparate. - Mircea Eliade\r\n', 'Beletristică'),
(18, 'Mircea Eliade', 'Maitrey', 'Cartex', 2006, 1, 'Maitreyi, crescută într-o civilizație a semnelor și a pudorii, atrage pe Allan într-un joc erotic complicat și imprevizibil. O privire insistență este un cod ce trebuie descifrat, o floare în care este ascuns un fir de păr este un simbol, atingerea mâinilor este deja un act de curaj și o trădare a vechii iubiri. Când într-o zi, la masă, Maitreyi îi atinge intenționat piciorul, asta înseamnă o mare promisiune. Promisiunea este întărită de o coroniță de iasomie pe care sălbatica îmblânzită i-o aruncă într-o seară de pe terasă. Este dovada logodnei. Logodna propriu-zisă se săvârșește la lacuri, în fața apei, a pădurii și a cerului. Este o logodnă mistică, un jurământ cosmic, un poem de o frumusețe barbară.\r\n\r\nMaitreyi este, oricâte nemulțumiri ar trezi, un roman viu, substantial, cu o deschidere nouă spre problematica omului modern (un spirit, între altele, călător, confruntat în experiențele lui existențiale cu mentalități înrădăcinate în ceea ce antropologii numesc cultura de profunzime). Nu atât exotismul - deși nici acesta nu poate fi ignorat - este elementul inedit în romanul lui Eliade, ci un spirit nou de a gândi destinul omului în secolul XX, o voință clară de sincronizare cu spiritul timpului. Intelectualizarea conflictului epic este un prim element. (…) O capodoperă? Un roman, oricum, substantial, viabil după mai bine de o jumătate de secol de când a fost scris. Eliade încearcă să construiască, după o formulă a lui Bachelard, o mitologie a seducției. Reușește în bună parte. - Eugen Simion\r\n', 'Beletristică'),
(19, 'Robert J. Sternberg', 'Manual de creativitate', 'Polirom', 2005, 2, 'Cartea oferă o analiză comprehensivă a evoluției procesului de creativitate de-a lungul timpului și cuprinde informații despre temele majore presupuse de un asemenea subiect, despre originile și metodele optime de abordare. Opiniile cuprinse în volumul de față sunt legitime științific și devin puncte de referință prin larga lor vehiculare internațională. La aceste opinii se vor referi, mult timp, cursurile academice din întreaga lume, comunicările științifice din cadrul manifestărilor internaționale, programele de formare profesională în domeniile atât de diverse ale manifestării creativității, ca parte a talentului individual și colectiv. Volumul reprezintă o sursă extraordinară pentru orice student din domeniul științelor psihosociale și pedagogice, dar și un ghid necesar tuturor celor interesați de gândirea creativă.\r\n', 'Sociologie'),
(20, 'Ioan Slavici', 'Mara', 'Vox', 2006, 1, 'Mara, unul dintre cele mai importante romane ale literaturii române, poate deschide dialoguri fertile atât cu istoricii literari de azi, cât și cu sociologii de mâine, atât cu cei care vor să cunoască secolul al XIX-lea al periferiilor Europei centrale, cât și cu cei care vor să se așeze temeinic în secolul XX al ofensivelor feministe. Romanul femininului învingător, Mara le poate propune regizorilor imagini retro memorabile dintr-o lume care a fost. Și personaje care merită marile competiții ale artei, fie teatrale sau cinematografice.\r\n\r\nMara este romanul socialității învingătoare pe toate planurile, în confruntarea cu indivizii pe care natura și vârsta îi împing temporar la nesupunere. Colectivitatea face legea pe care individul este ținut să o respecte; el nu simte deocamdată, în această necesitate individuală, caracterul opresiv. O primește ca și cum legea tuturor ar fi bună și pentru el. - N. Manolescu\r\n', 'Beletristică'),
(21, 'Ioan Slavici', 'Moara cu noroc.Pădureanca', 'Art ', 2006, 1, 'Plasată în colecția \"Clasici Români\", cartea de față se alătură celorlalte, care valorifică potențialul creativ al poporului român prin reprezentanți de seamă. Prin cuvântul clasic se poate înțelege clasicismul ca și curent literar, dar și o valoare perenă, ce străbate timpul și care, prin repetiție, constantă, se păstrează în conștiința unei comunități. Desfășurarea existenței în cercul strâmt între viață și moarte păstrează conștiința trează a unui popor, a unei națiuni în concertul culturii universale.\r\n\r\nColecția \"Clasici Români\" nu face altceva decât să reînvie câteva dintre cele mai importante creații artistice ale celor ce au plasat valorile naționale în context universal și să refacă astfel geneza și moartea, pentru a se păstra vie viața spirituală.\r\n', 'Beletristică'),
(22, 'Marin Preda', 'Moromeții vol.1', 'Cartex', 2006, 1, 'Prin \"Moromeții\", Marin Preda ne vorbește de țărani cum nu se mai vorbise până la el. Într-o literatură saturată, aparent, de materia vieții țărănești, această apariție părea imposibilă. Izvorul părea epuizat și o adevărată campanie pragmatică împotriva literaturii cu subiecte rurale contribuise și ea, decisiv, la consolidarea impresiei. Marin Preda ne descoperă totuși o lume inedită, scăldată într-o lumină solară care alungă tenebrele. - Mihai Ungureanu\r\n', 'Beletristică'),
(23, 'Marin Preda', 'Moromeții vol.2', 'Cartex', 2006, 1, '\"Moromeții\" este povestea nu numai a țăranului român și a schimbărilor prin care acesta trece, ci o poveste actuală a romanului în general, al cărui caracter este subliniat de umorul negru și conexiunea cu viața la sat. \"Moromeții 2\" a fost ecranizat în 2018 de Stere Gulea, film în care au fost reunite scene și stări din mai multe cărți ale lui Marin Preda. Fascinant este felul în care românii de azi s-au regăsit în film, faptul că istoria pare a se repeta sub forme diferite, dar cu aceeași esență.\r\n', 'Beletristică'),
(24, 'Ioan Slavici', 'Nuvele', 'Corint', 2006, 8, 'Prin nuvelele sale, Slăvici aduce un elogiu învățăturii, muncii intelectuale, dar reușește să surprindă deopotrivă o întreagă societate, cu obiceiurile, problemele și tradițiile ei dintr-un anumit loc și moment istoric. În descrierile de natură dovedește sobrietate, apelând întotdeauna la sugerarea mediului întâmplării și nu la descrierea în sine a naturii. \r\nSchițele și nuvelele lui Slăvici, luminate adeseori de preocupări de ordin moral, aduc în scenă personaje cu o psihologie lipsită de mari complicații, în adâncurile căreia ochiul scriitorului pătrunde și notează cele mai subtile nuanțe ale sentimentului, pe care le traduce sumar, într-un cuvânt sau un gest cu rădăcini adânci. (DIMITRIE POPOVICI)\r\n', 'Beletristică'),
(25, 'Ion Luca Caragiale', 'Nuvele si povestiri', 'Art ', 2006, 1, 'Plasată în colecția \"Clasici Români\", cartea de față se alătură celorlalte prin care se valorifică potențialul creativ al poporului român prin reprezentanți de seamă. Prin cuvântul \"clasic\" se poate înțelege clasicismul ca și curent literar, dar și o valoare perenă ce străbate timpul și care, prin repetiție constantă, se păstrează în conștiința unei comunități. Desfășurarea existenței în cercul strâmt între viață și moarte menține conștiința trează a unui popor, a unei națiuni în concertul culturii universale.\r\n\r\nColecția \"Clasici Români\" nu face altceva decât să reînvie câteva dintre cele mai importante creații artistice ale celor ce au plasat valorile naționale în context universal și să refacă astfel geneza și moartea pentru a se păstra vie viața spirituală. Volumul \"Nuvele și povestiri\" semnate de I.L. Caragiale, prin structura sa, cuprinde nuvelele și povestirile cunoscute ale scriitorului, care trezesc la viață o lume dispărută, dar a cărei mentalități și atitudini au rămas eterne, ca întreaga operă a lui Caragiale, mereu actuală, mereu tânără.\r\n', 'Beletristică'),
(26, 'Vasile Voiculescu', 'Nuvele și povestiri', 'Cartex', 2006, 1, 'Cuprins:\r\nFlorile. Poemul Hanului cu urși. Ciobănița. Șarpele Aliodor. Taina gorunului. Capul de zimbru. Căprița de vis. Șakuntala. Iubire magică. Lostrita. Ultimul Berevoi. Pescarul Amin.\r\n', 'Beletristică'),
(27, 'Nichita Stănescu', 'Opera Poetică', 'Cartier', 2007, 1, 'Opera Poetică, de Nichita Stănescu', 'Beletristică'),
(28, 'Mihai Eminescu', 'Pagini alese', 'Vox', 2006, 1, 'Eminescu este marele subiect al poeziei românești. El este viu în conștiința poporului, este studiat, interpretat, omagiat, învățat cu plăcere sau defăimat și, toate acestea la un loc, dovedesc rolul dominant pe care îl ocupă Eminescu în cultură și în sufletul românilor.\r\n\r\nPe Eminescu nimeni nu îl poate uita, nu-l poate tăgădui: \"Oricât de tare ar fi cântat cocoșii a treia oară, pe el nimeni nu l-a tăgăduit.\" – G. Bogza\r\n\r\nAtât timp cât pe aceste pământuri vor trăi români iubitori de codru, de mare, de tei, iubitori de dreptate și adevăr, doritori de bine pentru țară, Eminescu le va fi simbol și ideal.\r\n', 'Beletristică'),
(29, 'George Bacovia', 'Plumb', 'Humanitas', 2007, 3, 'Plumb este o poezie scrisă de George Bacovia în 1900, finisată în 1902 și publicată în 1916 în revista „Versuri”, sub pseudonimul George Andoni. Discursul poetic este conceput sub forma unui monolog tragic în care poetul exprimă o stare sufletească de disperare, și lipsă a oricărei speranțe. Poezia produce o puternică impresie la citirea ei de către autor în 1903 la salonul literar al lui Alexandru Macedonski.\r\n\r\nPoezia a fost scrisă pentru prima dată în 1900. La vremea aceea, poetul, în vârstă de 19-20 de ani, era în cursul de a aplica la Școala Militară din Iași, de unde se retrase după un trimestru. Un an mai târziu se înscrise la gimnaziul din Bacău. Acesta luă cunoștința cu Alexandru Macedonski în 1902 și se formă artistic între anii 1903–1904 în mediul simbolist, frecventând cenaclul poetului. Rezultatul, volumul de poezii Plumb (1916), reprezintă rodul selecții dintre 50 de poeme, selecție determinată de o anumită fizionomie poetică care coincidea, în mare măsură, cu norma estetică dominantă la începutul secolului XX. George Bacovia dorise să devină un simbolist, un urmaș al lui Macedonski și al lui Tradem (pseudonimul lui Traian Demetrescu) și un emul al lui Edgar Allan Poe, Charles Baudelaire, Paul Verlaine și Maurice Rollinat.', 'Beletristică'),
(30, 'Gabriele D\'Annunzio', 'Poate că da, poate că nu', 'Art ', 2008, 4, 'Romanul (ecranizat în 1920, într-un film mut, alb-negru) i-a fost inspirat lui D’Annunzio de propria iubire pentru contesa Giuseppina Mancini. La data publicării, romancierul a fost silit să fugă din Italia, ca să scape de creditori, stabilindu-se în Franţa, unde şi-a consumat nostalgia fostei iubiri alături de alte femei.\r\nDespre Forse che sì forse che no (1910), autorul însuşi spunea, într-o scrisoare din 1908, că este „un roman de pasiuni mortale“. Cuvântul-cheie din titlu, „poate“, devine un laitmotiv pentru nesfârşitele meditaţii şi ezitări ale Isabellei, îndrăgostită de Paolo Tarsis, dar şi măcinată de remuşcări din cauza propriilor sentimente. Nehotărârea ei o face, în ochii amantului, cu atât mai atrăgătoare. Isabella este obsedată de imaginea surorii ei, Vana, la rându-i îndrăgostită de Paolo, care însă nu-i împărtăşeşte iubirea. Pe cele două surori le frământă dragostea şi gelozia şi le despart ideea suicidului şi nebunia.\r\n\r\nRomanul (ecranizat în 1920, într-un film mut, alb-negru) i-a fost inspirat lui D’Annunzio de propria iubire pentru contesa Giuseppina Mancini. La data publicării, romancierul a fost silit să fugă din Italia, ca să scape de creditori, stabilindu-se în Franţa, unde şi-a consumat nostalgia fostei iubiri alături de alte femei.', 'Beletristică'),
(31, 'George Coșbuc', 'Poezii', 'Maxim Bit', 2006, 3, '\"George Coșbuc a fost, înainte de Primul Război Mondial, cel mai popular poet român, așa cum va fi G. Topârceanu, după același război, și Nichita Stănescu, după cel de-al Doilea. Manualele de școală își au până în prezent în G. Coșbuc unul dintre favoriții nelipsiți din ultimul secol. Titu Maiorescu a văzut în G. Coșbuc pe cel mai de seamă urmaș al lui Eminescu. N-a fost să fie. Dacă Eminescu a deschis drumul noii poezii, aceleia din secolul XX, Coșbuc l-a închis pe acela al vechii poezii din secolul XIX. Poezia lui Coșbuc este astăzi citită mai ales de elevi, părând și fiind o poezie care evocă adolescența și copilăria în lumea satului de odinioară. La 150 de ani de la nașterea poetului Baladelor și idilelor, întrebarea este dacă acest sat, cu obiceiurile și distracțiile lui, mai semăna cu acela contemporan. Probabil că nu. Doar că sufletul copilului lui Coșbuc este sufletul copilului universal. Iarna pe uliță este și astăzi iarna săniușului copiilor noștri!\" - NICOLAE MANOLESCU\r\n', 'Beletristică'),
(32, 'Mihai Eminescu', 'Poezii', 'Cartex', 2006, 1, 'Eminescu a dat poeziei românești dimensiunile care îi lipseau înainte. Lumea în care ne introduce Eminescu este o lume de mare vastitate în spațiu și în timp și în care privirea cugetătorului pătrunde până în punctele cele mai tăinuite ale sufletului omenesc și până în concepțiile cele mai înalte ale rațiunii.\r\n', 'Beletristică'),
(33, 'Vasile Alecsandri', 'Poezii', 'Maxim Bit', 2006, 9, 'Vasile Alecsandri a fost un poet, dramaturg, folclorist, om politic, ministru, diplomat, academician român, membru fondator al Academiei Române, creator al teatrului românesc și a literaturii dramatice în România, personalitate marcantă a Moldovei și apoi a României de-a lungul întregului secol al XIX-lea.\r\n\r\nPutem spune că Vasile Alecsandri este primul scriitor român complet, cu o operă demnă de a fi luată în seamă în toate cele trei compartimente ale literaturii – poezie, teatru și proză.\r\n', 'Beletristică'),
(34, 'Ion Creanga', 'Povești și povestiri', 'Corint', 2006, 1, 'Cum a furat Harap-Alb salatele din Grădina Ursului? Cât de moi trebuie să fie posmagii, cum a izbutit Dănilă Prepeleac să scape de sărăcie și cine a avut acul în cojocul soacrei cu trei nurori?\r\n\r\nCu umorul lor fabulos, povestile și povestirile lui Ion Creangă au bucurat multe generații - iar acum le puteți citi într-un format mai accesibil, care respectă ortografia vremurilor noastre, pentru a face textul mai ușor de parcurs de către copii.\r\n', 'Beletristică'),
(35, 'Bogdan Petriceicu Hașdeu', 'Răzvan și Vidra', 'Corint', 2007, 8, 'Răzvan și Vidra este una dintre cele mai bune drame din literatura română. [...]\r\n\r\nEste drama individului apăsat de prejudecata publică. Răzvan este un paria îmbrăcat în hainele efemere ale puterii, în lupta cu un factor monstruos de nedefinit și în condiție cu atât mai tragică cu cât admiratia tuturor se amestecă cu o compasiune jignitoare. Destinul implacabil din tragedia greacă a fost înlocuit aici cu reaua naștere apăsând asupra geniului. - George Călinescu, Istoria literaturii române de la origini până în prezent\r\n', 'Beletristică'),
(36, 'Daniel Defoe', 'Robinson Crusoe', 'Național', 2004, 2, 'Robinson Crusoe, personajul care este și naratorul cărții, povestește că s-a născut în 1632 în orașul York din Anglia. Tatăl său era un emigrant german și s-a căsătorit cu mama sa. Numele ei de fată era Robinson. Pe povestitor îl chema deci Robinson Kreutznaer, dar, din cauza că englezii nu puteau pronunța un astfel de nume, familia i-a adaptat o formă engleză - Crusoe. Robinson a fost al treilea fiu; fratele său mai mare s-a înrolat și a murit în război, iar al doilea frate mai mare a dispărut și nu s-a mai știut nimic de el.\r\n\r\nCând Robinson avea 19 ani, a plecat fără aprobarea părinților la Londra, unde s-a îmbarcat pe o corabie. Prima călătorie a fost încununată de succes și el s-a întors în Anglia cu puțină avere, ceea ce l-a determinat să plece iar pe mare. În a doua călătorie, însă, corabia i-a fost atacată de pirați și Robinson a fost luat în robie în Africa, dar în scurt timp a reușit să evadeze și a fost salvat pe o navă care mergea în Brazilia. Ajuns în Brazilia, și-a făcut acolo o plantație, care mergea foarte bine.\r\n\r\nMânat de setea de aventură, Crusoe se îmbarcă din nou pe o corabie, care naufragiază în urma unei furtuni cumplite. Singurul supraviețuitor al naufragiului eșuează pe malul unei insule pustii, situată în afara rutei obișnuite a navelor. Reușește să recupereze de pe epavă arme, gloanțe, praf de pușcă, îmbrăcăminte, o ladă cu scule și multe lucruri necesare pentru supraviețuire.\r\n', 'Beletristică'),
(37, 'Jules Verne', 'Steaua Sudului', 'Ion Creangă', 1984, 1, 'Cartea este un roman scris de Jules Verne a cărui acțiune se petrece în Griqualand, în Africa de Sud, unde inginerul minier Cyprien Mere conduce studii de chimie organică asupra depozitelor de diamante.\r\nEroul vrea să se căsătorească cu Miss Alice Watkins, dar tatăl acesteia refuză deoarece Mere nu era bogat. Cyprien începe fabricarea unui diamant artificial cu ajutorul căruia să obțină mâna lui Alice.\r\n\r\nÎn urma unei experiențe norocoase, el obține un enorm diamant negru, supranumit Steaua Sudului, dar piatra dispare în scurt timp după tăiere.\r\n', 'Beletristică'),
(38, 'Cristian Teodorescu', 'Tainele inimei', 'Cartea Românească', 2005, 1, 'Romanul \"Tainele inimii\", distins cu Premiul Academiei Române în 1990, se află la a doua ediție.\r\n\r\n\"N-am schimbat nimic în această reeditare față de prima ediție a \"Tainelor inimii\", din cel puțin două motive. Cartea a devenit între timp un fel de document de epocă. Dacă mi-aș fi permis să intervin în ea, aș fi făcut cam același lucru ca martorii proceselor de azi, care își schimbă declarațiile după împrejurări. În afara de asta, romanul urmărește un anumit sindrom, cel de sufocare, de care sufereau și suferă mulți intelectuali români.\" (Cristian Teodorescu)\r\n\r\nDacă până la Revoluție \"Tainele inimii\" a fost un document de ficțiune, după 1989 autorul a surprins realitatea socială mulându-se pe ficțiunea sa: \"Povești asemănătoare celei prin care trece personajul principal al acestei cărți am auzit după Revoluție de la câteva zeci de persoane de bună condiție care și-au părăsit familia, slujba și identitatea, din cauza că simțeau că se sufocă, dacă n-ar fi ales această cale. Trăiesc din te miri ce, iar câțiva încearcă să se întoarcă la viața pe care au abandonat-o. Nu izbutesc, fiindcă simt din nou că sunt strânși de beregată: nu de cineva anume, ci de ceva impalpabil care supraviețuiește în România și după 1989.\" (Cristian Teodorescu)\r\n', 'Beletristică'),
(39, 'Marin Sorescu', 'Teatru', 'Minerva', 2006, 1, 'Capodoperele nu ne cer să le iubim, dar cu siguranță ne cer să le citim. Vă recomandăm seria \"100 DE ANI DE CARTE ROMÂNEASCĂ\", lansată în anul în care editura noastră împlinește 100 de ani.\r\nLectură plăcută, dragi cititori! Nicolae Manolescu\r\n\r\nPrivite retrospectiv, creațiile dramatice soresciene ni se înfățișează ca un spectacol al inteligenței în mișcare. Piesele lui Marin Sorescu, precise și ireverențioase față de convenții, greu de fixat într-o formulă, trăiesc într-o continuă mobilitate a scriiturii. Autorul era convins - după cum spunea adesea - că nu genul sau forma contează, ci substanța pe care autorul o poartă cu sine și pe care o toarnă într-o formă sau alta, în funcție de inspirație sau de propensiunea conținutului înșiși. Aceasta nu l-a împiedicat să fie unul dintre marii inovatori ai literaturii noastre postbelice, atât în poezie, cât și în teatru. - Răzvan Voncu\r\n', 'Beletristică'),
(40, 'Vasile Alecsandri', 'Teatru', 'Art ', 2006, 1, '\"Se poate spune, fără exagerare, că în biruirea dificultăților de început ale teatrului românesc și în dezvoltarea sa de-a lungul unei jumătăți de veac, contribuția lui Alecsandri a fost hotărâtoare. El a dat limbii cursivitate și, firesc, a reușit, pentru întâia oară până la Caragiale, să restituie senzația vorbirii autentice a oamenilor, potrivit cu starea socială și profesiunea lor, să-i caracterizeze prin dialog. Pe tărâmul construcției, a experimentat o mare diversitate de genuri și forme teatrale...\" (G.C. NICOLESCU)\r\nCuprins: Chirița în Iași sau Două fete să o nenorocească • Chirița în Provincie • Despot-Vodă • Postfață • Tabel cronologic • Aprecieri critice\r\n', 'Beletristică'),
(41, 'Andre de Peretti', 'Tehnici de comunicare', 'Polirom', 2007, 2, 'Traducere de Gabriela Sandu\r\nÎn viața de zi cu zi, acasă sau la serviciu, fiecare dintre noi trebuie să transmită anumite mesaje și să obțină anumite informații; comunicarea este, prin urmare, esențială. Andre de Peretti, Jean-André Legrand și Jean Boniface propun o serie de tehnici și instrumente, susținute de exemple practice, care să ne permită o mai bună comunicare cu cei din jur și cu noi înșine.\r\n\r\nCuprins: Jocuri ale tehnicilor de grup • Exerciții de comunicare • Formarea pentru conversație • Dispozitive de simulare\r\n', 'Sociologie'),
(42, 'Lyman Frank Baum', 'Vrăjitorul din Oz', 'Național', 2004, 2, 'Există o tendință puternică a scriitorilor moderni de a introduce misticism sau ocultism în scrierile lor. Pe măsură ce avem din ce în ce mai multe cunoștințe, dorința noastră de cunoaștere crește și suntem mai puțin satisfăcuți să rămânem în ignoranță. [...]\r\n\r\nAtunci când am scris \"Vrăjitorul din Oz\", a fost o inspirație pură. Mi-a venit din nimic. Uneori, cred că Marele Autor mi-a trimis un mesaj, și tot El m-a folosit ca instrument al Său. Eu, s-a întâmplat să fiu acest mijlocitor. Și cred că cheia magică mi-a fost dată pentru a deschide ușile înțelegerii, bucuriei, păcii și fericirii. (Oscar Wilde)\r\n', 'Beletristică'),
(43, 'Ion Luca Caragiale', 'O scrisoare pierdută', 'Ion Creangă', 1995, 1, 'Teatrul lui Caragiale a rămas în conștiința colectivă mai ales prin intermediul comediei. Toate cele patru texte dramatice concretizează istoric o lume, astfel încât scriitorul își proiectează întreaga viziune clasică în spațiul românesc, într-un moment în care burghezia se afla în zorii apariției sale.\r\n\r\nPiesa de teatru \"O scrisoare pierdută\" cuprinde imaginea societății românești la nivelul politicii din a doua jumătate a secolului al XIX-lea. Aici se înfruntă două grupări ale partidului aflat la putere. Pe de o parte, Zaharia Trahanache, Tipătescu, Zoe, Ghita Pristanda, Farfuridi, Brânzovenescu, dintre cei aflați la putere, și cei din opoziție, unde se face vizibil Catavencu, directorul ziarului Răgnetul Carpaților, dar și Agamemnon Dandanache, cel trimis de la București de forța puterii și care reușește să se impună doar pentru că a fost trimis de la centru. Întreaga piesă excelază prin categoriile comicului văzut în diverse ipostaze...\r\n', 'Beletristică'),
(44, 'Sorin Cristea', 'Fundamentele pedagogiei', '', 1994, 4, 'Prin cele trei secțiuni ale sale, volumul reprezintă o introducere în pedagogia generală și acoperă o zonă semnificativă din teoria curriculumului (curriculumul tratat ca paradigmă, mod de abordare a teoriei pedagogice), având deschidere către teoria instruirii și a evaluării. Prima parte analizează statutul epistemologic al pedagogiei ca știință socioumană specializată în studiul educației, în timp ce a doua secțiune definește și discută, din perspectiva paradigmii curriculumului, conceptele pedagogice fundamentale, aflate la baza demersului epistemic al tuturor științelor educației. Ultima parte analizează direcțiile principale de evoluție a educației: educația permanentă, autoeducația și valorificarea deplină a educabilității. Fundamentele pedagogiei constituie o lectură utilă pentru practicienii și specialiștii în științele educației, precum și pentru studenții de la facultățile de profil.\r\n', 'Sociologie'),
(45, 'George Topîrceanu', 'Balade vesele și triste', 'Libris', 2004, 4, 'Cărți clasice, alese cu grijă, la care ne reîntoarcem adesea, pentru noile generații de elevi, profesori, părinți.\r\n\r\nExpresive, amuzante, tandre, înduioșătoare, colorate în cele mai frumoase nuanțe, poeziile lui G. Topîrceanu ne invită să le descoperim ori să le redescoperim și să le savurăm fără rețineri. \"Balada unui greier mic\", \"Sfârșit de vară\", \"Rapsodii de toamnă\" sunt doar câteva dintre instantaneele din albumul de fotografii al naturii pe care poetul l-a surprins cu talent și cu o sclipire poznasă în priviri.\r\n', 'Beletristică'),
(46, 'Hector Malot', 'Singur pe lume', 'Libris', 2004, 8, '\"Singur pe lume\" este povestea unui copil găsit pe stradă, care ajunge să trăiască întâmplări ce trimit cu gândul la prietenie, deznădejde, pesimism, dar și optimism, pierdere, dar și regăsire, toate puse în pagină cu multă candoare. Totul se termină cu bine, căci copilul își găsește familia adevărată, familia mult visată, ca răsplată pentru bunătatea sa, după ce a fost pus atât de mult la încercare. Finalul fericit este încântător și pentru cititor, care trăiește alături de micul hoinar peripețiile prin care acesta trece. Lectura acestei cărți îl poate face chiar și pe cititorul matur să retrăiască anii copilăriei alături de eroii ei și cu siguranță va face tot posibilul pentru ca orice copil să citească \"Singur pe lume\". Micii cititori vor fi încântați.\r\n', 'Beletristică'),
(47, 'Gabriel Liiceanu', 'Jurnalul de la Păltiniș', 'Humanitas', 2005, 1, 'Jurnalul de la Paltiniş - jurnalul momentelor petrecute de Gabriel Liiceanu în preajma lui Noica - a fost bestseller al anilor \'80, când se vindea pe sub mână şi se împrumuta numai prietenilor de încredere.\r\n\r\nEdiţia a doua, revăzută şi adăugită cu paginile cenzurate în 1983, a fost publicată de Humanitas în 1991 şi din acel an Jurnalul s-a vândut în peste 50 000 de exemplare. Împreună cu Epistolarul, Jurnalul de la Păltiniş reconstituie în beneficiul tinerei generaţii de astăzi premisele mitului de ordin cultural născut, în anii \'80, în jurul personalităţii lui Noica.', 'Memorii,biografii,jurnale'),
(48, 'Florin Măceșanu', 'Fizică:probleme și teste pentru gimnaziu', 'Corint', 2006, 1, 'Cuprinzând probleme pentru înțelegerea și fixarea cunoștințelor, teste de verificare și probleme date la concursuri și olimpiade școlare, lucrarea pune la dispoziția elevilor de gimnaziu un material didactic important pentru aprofundarea noțiunilor de fizică predate în clasele VI-VIII.\r\n\r\nStructurată pe patru capitole - mecanică, fenomene termice, electricitate și optică geometrică -, fiecare debutând cu succinte expuneri teoretice, cartea de față acoperă în întregime programa actuală de fizică pentru gimnaziu.\r\n\r\nGradul de dificultate al problemelor variază de la simplu la complex, iar răspunsurile sau rezolvările detaliate (acolo unde este cazul) le permit elevilor să-și testeze stadiul pregătirii.\r\n', 'Manuale și auxiliare școlare'),
(49, 'Gabriel Liiceanu', 'Despre limită', 'Humanitas', 2005, 1, 'Această carte despre limită este o apologie a vagului. Lucruri vagi, poate cele mai vagi, sunt omul, Dumnezeu, libertatea. Vagul este opusul precisului. Vagul este ceea ce rămâne după traversarea unui spațiu populat cu limite. Limita îl închide mai întâi pe om în spațiul precisului. Problema este cum să parcurgem apoi treptele precisului pentru a ajunge la lucrurile vagi.\r\n', 'Filozofie'),
(50, 'Gabriel Liiceanu', 'Despre minciună', 'Humanitas', 2006, 1, 'Mi-am propus să vă vorbesc despre minciună, ceea ce înseamnă despre un lucru pur omenesc: numai omul poate minți, pentru că numai omul are parte de un „lucru\" care poate să exprime și care, exprimând, se poate mișca în două direcții total opuse: adevărul și falsul intenționat.\r\nAcest „lucru\" este limba. Voi vorbi despre minciună nu în sensul ei „privat\", ci în cel „public\", așadar voi vorbi despre minciuna colectivă, în care unul sau mai mulți îi mint pe mulți care la rândul lor sunt fie mintiți, fie mint în corpore, trăind împreună cu cei care îi mint, într-un vast scenariu al minciunii.\r\n', 'Filozofie'),
(51, 'Adina Baran Pescaru', 'Parteneriat în educație', 'Minerva', 2005, 1, 'Parteneriat în educație, de Adina Baran Pescaru', 'Practice și timp liber'),
(52, 'Florica Tibea', 'Anatomia omului, atlas școlar ', 'Corint', 2017, 8, 'Lucrarea se remarcă prin modul de prezentare a structurilor interne și externe ale diverselor organe și sisteme ce alcătuiesc corpul uman, pornind de la celulă și țesuturi pentru a ajunge la sistemele locomotor, nervos, endocrin, digestiv, circulator, respirator, excretor și încheind cu sistemul reproducător și etapele formării embrionului uman.\r\n\r\nAtlasul se impune în atenția tuturor celor interesați prin acuratețe, conciziunea și claritatea planșelor reproduse, prin diversitatea mijloacelor științifice și grafice folosite pentru a oferi imagini concludente ale structurilor anatomice, constituind prin aceasta o prezență inedită în peisajul lucrărilor de specialitate.\r\n', 'Manuale și auxiliare școlare');

--
-- Indexuri pentru tabele eliminate
--

--
-- Indexuri pentru tabele `carte`
--
ALTER TABLE `carte` ADD FULLTEXT KEY `Descriere` (`Descriere`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
